### ISSUE TITLE
Use REST API to APIs.guru(catalog of Swagger files).

### ISSUE THREAD

**Issue by IvanGoncharov** [ardoq/ardoq-swagger-addon#15]
Hi,
I saw that you use snapshot of my [catalog](https://github.com/APIs-guru/api-models):
https://github.com/ardoq/ardoq-swagger-addon/tree/master/resources/swagger
Since then I added new APIs, updated existing ones and fix many bugs.
Did you consider using [REST API](https://github.com/APIs-guru/api-models/blob/master/API.md) to my catalog?

**Comment by Molyna** [comment]
Hey, thanks for the link. Didn't know about this, only saw the files as a tar. 

I switched them out and parsed the endpoint you had set up and added a note to the readme that our test files where being taken from your repo.

Let me know if you think we should do a different setup than that.

**Comment by IvanGoncharov** [comment]
@Molyna Thank you.

> Didn't know about this, only saw the files as a tar.

Very interesting, how did you get it?
I try to help early adopter of my services, so I run multiple Github search queries to discover all projects which using it or specs from it.
That's how I found your project but I'm not aware of tar archive :disappointed: 

> Let me know if you think we should do a different setup than that.

It's perfect, you use dedicated API and that's most important thing.
I also added your project into list of integrations:
https://github.com/APIs-guru/api-models#existing-integrations

Plus I created badge: [![Tested on APIs.guru](http://apis-guru.github.io/api-models/banners/tested_on_banner.svg)](https://github.com/APIs-guru/api-models)
If you like it, you can add this line into README:
```
[![Tested on APIs.guru](http://apis-guru.github.io/api-models/banners/tested_on_banner.svg)](https://github.com/APIs-guru/api-models)
```

P.S. You can use my catalog not only for testing but to provide you users to get data from public APIs.
If you interested we can talk on Skype(ivangon4arov) or Hangouts(ivan.goncharov.ua@gmail.com).
