### ISSUE TITLE
Improve validation error response

### ISSUE THREAD

**Issue by ebaxt** [ardoq/ardoq-swagger-addon#3]
Right now it only returns top level messages, but the interressting bits are in the nested messages. Maybe better to just allow to download the json error dump.

Example data: http://theapistack.com/data/youtube-for-dev/youtube-data-api-swagger.json

http://json-schema-validator.herokuapp.com/

**Comment by Molyna** [comment]
Issue is that we sometimes have new lines in descriptions of parameters. Need to replace the newline with <br>
