### ISSUE TITLE
If you try to import from beta.ardoq you get switched to app.ardoq.com

### ISSUE THREAD

**Issue by istendera** [ardoq/ardoq-swagger-addon#4]

**Comment by ebaxt** [comment]
@Molyna Could you check if we can use HTTP referer to redirect users to the correct ardoq subdomain?

**Comment by Molyna** [comment]
I am assuming the issue lies with  

(str (:base-url config) "/app/view/workspace/" wid "?org=" org))

A referer should be simple enough to implement with something like but we lose the redirect to the new workspace created. 

(let [back (get (:headers request) "referer")]
  (redirect-to back))
