### ISSUE TITLE
Re use workspace when user specifies existing workspace name

### ISSUE THREAD

**Issue by kristianhelgesen** [ardoq/ardoq-swagger-addon#8]
When integrating this add-on in an Continuous Integration system, one wishes to update a single workspace. 
Also existing components should be updated, not replaced to retain manually created relations

**Comment by Molyna** [comment]
Got some design choices to make. How do we want to do with components that are part of importing? Do we want to overwrite them? Do we want to overwrite any that haven't been edited in Ardoq?

Doubt strongly we want duplicate components

**Comment by Molyna** [comment]
Should be ready but needs code reviewing.

Pull request #10

**Comment by ebaxt** [comment]
@Molyna Can you have a look at https://github.com/ardoq/ardoq-backlog/issues/16 as well?
